[project]
name = "trae-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "chromadb>=0.5.0",
    "dotenv>=0.9.9",
    "langchain>=1.1.2",
    "langchain-deepseek>=1.0.1",
    "langchain-qwq>=0.3.1",
    "langchain-text-splitters>=1.0.0",
    "numpy>=2.3.5",
    "openai>=2.9.0",
    "pydantic-settings>=2.12.0",
    "sentence-transformers>=5.1.2",
]
